version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: immowealth
    ports:
      - "5432:5432"
  server:
    depends_on:
      - postgres
    image: ghcr.io/mathisburger/immowealth:latest
    platform: linux/amd64
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/immowealth
    ports:
      - "8081:8080"