quarkus:
  native:
    resources:
      includes: publicKey.pem
  http:
    cors:
      ~: true
      origins: /.*/
  datasource:
    db-kind: postgresql
    username: postgres
    password: mysecretpassword
    jdbc:
      url: jdbc:postgresql://localhost:5432/immowealth
  rest-client:
    geocoding:
      url: https://nominatim.openstreetmap.org/
      scope: jakarta.inject.Singleton
    foreignExchangeRate:
      url: https://commander.commerzbank.com/
      scope: jakarta.inject.Singleton
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: create
immowealth:
  defaultMail: kontakt@mathis-burger.de

mp:
  jwt:
    verify:
      issuer: http://localhost
      publickey:
        location: publicKey.pem
  
  quarkus.native.resources.includes=publicKey.pem