on:
  push:
    branches: [main]
#  release:
#    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: immowealth
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=uber-jar
      - name: Start application
        run: |
          nohup ./gradlew --console=plain quarkusDev &
          for attempt in {1..20}; do sleep 1; if curl http://localhost:8080/; then echo ready; break; fi; echo waiting...; done

      - name: Get graphQL schema
        run: curl http://localhost:8080/graphql/schema.graphql >> web/schema.graphql