on:
#  push:
#    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: immowealth
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Setup OpenSSL JWT certificats
        run: |
          openssl genrsa -out rsaPrivateKey.pem 2048
          openssl rsa -pubout -in rsaPrivateKey.pem -out publicKey.pem
          openssl pkcs8 -topk8 -nocrypt -inform pem -in rsaPrivateKey.pem -outform pem -out privateKey.pem
          cp ./privateKey.pem ./src/main/resources/privateKey.pem
          cp ./publicKey.pem ./src/main/resources/publicKey.pem
      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=uber-jar
      - name: Start application
        run: |
          nohup ./gradlew --console=plain quarkusDev &
          for attempt in {1..20}; do sleep 1; if curl http://localhost:8080/; then echo ready; break; fi; echo waiting...; done
      - name: Generate schema
        run: curl http://localhost:8080/graphql/schema.graphql >> web/schema.graphql
      - name: Update schema
        run: |
          echo "scalar Date" >> web/schema.graphql 
          echo "scalar BigInteger" >> web/schema.graphql 
          echo "scalar DateTime" >> web/schema.graphql
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mathisburger
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/mathisburger/immowealth:latest
